# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: uptime-kuma.service.j2
    dest: /lib/systemd/system/uptime-kuma.service
    mode: "0644"
  notify: Restart uptime-kuma
- name: Service uptime-kuma is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: uptime-kuma
    state: started
    enabled: true
- name: Allow uptime-kuma port
  community.general.ufw:
    rule: allow
    port: "{{ uptime_kuma_cfg['UPTIME_KUMA_PORT'] | default(3001) }}"
    proto: tcp
  when: uptime_kuma_allow_connect_other_host | default(false)
