# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
      become: true
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    ## ユーザーのテスト
    - name: Test user
      block:
        - name: Check user
          ansible.builtin.user:
            name: uptime-kuma
            system: true
          check_mode: true
          register: user_result
        - name: Assert user
          ansible.builtin.assert:
            that:
              - user_result is not changed
            fail_msg: "User uptime-kuma is not properly configured"
            success_msg: "User uptime-kuma is properly configured"
    ## グループのテスト
    - name: Test group
      block:
        - name: Check group
          ansible.builtin.group:
            name: uptime-kuma
            system: true
          check_mode: true
          register: group_result
        - name: Assert group
          ansible.builtin.assert:
            that:
              - group_result is not changed
            fail_msg: "Group uptime-kuma is not properly configured"
            success_msg: "Group uptime-kuma is properly configured"
    ## ファイルのテスト
    - name: Test file
      block:
        - name: Check virtualhost setting
          ansible.builtin.stat:
            path: /etc/default/uptime-kuma
          register: env_file_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - env_file_result.stat.exists
            fail_msg: "Environment file /etc/default/uptime-kuma not found"
            success_msg: "Environment file /etc/default/uptime-kuma exists"
    # サービスのテスト
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['uptime-kuma.service'] is defined
          - ansible_facts.services['uptime-kuma.service']['state'] == 'running'
          - ansible_facts.services['uptime-kuma.service']['status'] == 'enabled'
        fail_msg: "uptime-kuma service is not running or not enabled"
        success_msg: "uptime-kuma service is running and enabled"
    ## 待受ポートのテスト
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 3001 in listen_tcp_posts
        fail_msg: "Port 3001 is not listening"
        success_msg: "Port 3001 is listening"
